### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by danjng** [puppetlabs/puppetlabs-pe_gem#12]
Trying to handle some gems in Windows, here. Currently running PE 3.7.2

Getting the following error when trying to install a gem package locally:
`Provider pe_gem is not functional on this host`

Any ideas? Was it never intended to work on Windows?

**Comment by logicminds** [comment]
traditionally pe_gem is not required for windows because the pe version and open source version pointed to the same gem binary.  However, #10 just opened up support for using pe_gem on windows in order to backport an issue with the core provider.

**Comment by hunner** [comment]
Should be good to go in 0.2.0
